# Site settings
title: Matt Kirwan
email: mail@mattkirwan.com
description: > # this means to ignore newlines until "baseurl:"
Software Engineer at Sky Bet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.mattkirwan.com" # the base hostname & protocol for your site
twitter_username: mattkirwan
github_username:  mattkirwan

# Build settings
markdown: kramdown
