# Site settings
title: Matt Kirwan
job: Software Engineer at Sky Bet
email: mail@mattkirwan.com
description: > # Why isn't this working
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.mattkirwan.com" # the base hostname & protocol for your site
twitter_username: mattkirwan
github_username:  mattkirwan

# Build settings
markdown: kramdown
